title: Ryan Borchardt
logo: images/profile_photo.jpg
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist/Analyst with industrial data analysis experience 
  <br><br>
  Minneapolis, MN 
  <br><br>
  <a href="https://www.linkedin.com/in/ryan-borchardt/">View My LinkedIn Profile</a>


theme: jekyll-theme-minimal