title: Ryan Borchardt
logo: images/profile_photo.jpg
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst with a background in chemical engineering 
  <br><br>
  Minneapolis, MN 
  <br><br>
  <a href="https://www.linkedin.com/in/ryan-borchardt/">View My LinkedIn Profile</a> 

theme: jekyll-theme-minimal